name: Deploy Ionic Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different
permissions:
  contents: write  # Required for pushing to gh-pages
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Ionic project
      run: npm run build --prod -- --base-href "/home-expenses/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www  # Ensure Ionic build output goes here
